services:
  personal-blog-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 127221
